import * as THREE from 'three';
export function mountPlaza3D(el){
 const scene=new THREE.Scene(); scene.background=new THREE.Color(0x100d24); scene.fog=new THREE.Fog(0x100d24,16,42);
 const camera=new THREE.PerspectiveCamera(55,el.clientWidth/el.clientHeight,.1,100); camera.position.set(0,8,13); camera.lookAt(0,0,0);
 const renderer=new THREE.WebGLRenderer({antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.setSize(el.clientWidth,el.clientHeight); renderer.shadowMap.enabled=true; el.appendChild(renderer.domElement);
 scene.add(new THREE.HemisphereLight(0x8d79d9,0x241428,2)); const moon=new THREE.DirectionalLight(0xffd6e7,2); moon.position.set(-8,12,5); moon.castShadow=true; scene.add(moon);
 const ground=new THREE.Mesh(new THREE.CircleGeometry(15,64),new THREE.MeshStandardMaterial({color:0x30203b,roughness:.9})); ground.rotation.x=-Math.PI/2; ground.receiveShadow=true; scene.add(ground);
 const pathMat=new THREE.MeshStandardMaterial({color:0x8a7182,roughness:1}); const path=new THREE.Mesh(new THREE.PlaneGeometry(5,28),pathMat); path.rotation.x=-Math.PI/2; path.position.y=.015; scene.add(path);
 const water=new THREE.Mesh(new THREE.CylinderGeometry(2.2,2.4,.45,48),new THREE.MeshStandardMaterial({color:0x72526f})); water.position.y=.25; scene.add(water); const pool=new THREE.Mesh(new THREE.CylinderGeometry(1.8,1.8,.12,48),new THREE.MeshStandardMaterial({color:0x8ed6e7,emissive:0x31546b,emissiveIntensity:1})); pool.position.y=.52; scene.add(pool);
 const heartShape=new THREE.Shape(); heartShape.moveTo(0,0); heartShape.bezierCurveTo(-1,-1,-2,.4,0,2); heartShape.bezierCurveTo(2,.4,1,-1,0,0); const heart=new THREE.Mesh(new THREE.ExtrudeGeometry(heartShape,{depth:.18,bevelEnabled:true,bevelSize:.08,bevelThickness:.08}),new THREE.MeshStandardMaterial({color:0xff5d9e,emissive:0xb51f61,emissiveIntensity:2})); heart.scale.set(.35,.35,.35); heart.position.set(0,1.6,0); scene.add(heart);
 function tree(x,z,s=1){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.18,.25,1.6,8),new THREE.MeshStandardMaterial({color:0x54352f})); trunk.position.set(x,.8,z); scene.add(trunk); const crown=new THREE.Mesh(new THREE.SphereGeometry(1.15*s,12,10),new THREE.MeshStandardMaterial({color:0x263f37})); crown.position.set(x,2,z); scene.add(crown)}
 [[-6,-5],[6,-5],[-7,1],[7,1],[-6,7],[6,7]].forEach(p=>tree(...p));
 function lamp(x,z){const pole=new THREE.Mesh(new THREE.CylinderGeometry(.05,.07,2.3,8),new THREE.MeshStandardMaterial({color:0x17131a})); pole.position.set(x,1.15,z); scene.add(pole); const bulb=new THREE.Mesh(new THREE.SphereGeometry(.16,12,12),new THREE.MeshStandardMaterial({color:0xffd99a,emissive:0xffa84d,emissiveIntensity:5})); bulb.position.set(x,2.3,z); scene.add(bulb); const l=new THREE.PointLight(0xffad68,8,5);l.position.set(x,2.3,z);scene.add(l)}
 [[-3,-5],[3,-5],[-3,4],[3,4]].forEach(p=>lamp(...p));
 function avatar(x,color){const g=new THREE.Group(); const body=new THREE.Mesh(new THREE.CapsuleGeometry(.35,.8,5,10),new THREE.MeshStandardMaterial({color}));body.position.y=.85;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.35,16,12),new THREE.MeshStandardMaterial({color:0xe6b18d}));head.position.y=1.65;g.add(head);g.position.x=x;g.position.z=4;scene.add(g);return g} const a=avatar(-.7,0x7d6be8),b=avatar(.7,0xe85591);
 const target=new THREE.Vector3(0,0,4); renderer.domElement.addEventListener('pointerdown',e=>{const r=renderer.domElement.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hit=ray.intersectObject(ground)[0];if(hit){target.copy(hit.point);target.x=Math.max(-10,Math.min(10,target.x));target.z=Math.max(-10,Math.min(10,target.z));}});
 let t=0; function animate(){requestAnimationFrame(animate);t+=.01;heart.rotation.y=t; heart.position.y=1.65+Math.sin(t*2)*.08; const d=target.clone().sub(a.position);d.y=0;if(d.length()>.08){d.normalize();a.position.addScaledVector(d,.035);a.lookAt(target.x,a.position.y,target.z)} renderer.render(scene,camera)} animate();
 const resize=()=>{if(!el.isConnected)return;camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();renderer.setSize(el.clientWidth,el.clientHeight)};addEventListener('resize',resize);
}